#include <H:\PROJECTS\2024\12_Dataland\OCIO Aces 1.2\OCIOSharp\OpenColorIO\install\include\OpenColorIO\OpenColorIO.h>
#include <new>

extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat_VectorFloat___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat::*_0)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat__VectorFloat(OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat*__instance) { __instance->~VectorFloat(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat_VectorFloat(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt_VectorInt___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt::*_1)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt__VectorInt(OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt*__instance) { __instance->~VectorInt(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt_VectorInt(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_UniformData___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::*_2)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_UniformData(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData__UniformData(OpenColorIO_v2_4::GpuShaderDesc::UniformData*__instance) { __instance->~UniformData(); }
