#include <H:\PROJECTS\2024\12_Dataland\OCIO Aces 1.2\OCIOSharp\OpenColorIO\install\include\OpenColorIO\OpenColorIO.h>
#include <new>

class _0GpuShaderCreator : public OpenColorIO_v2_4::GpuShaderCreator { public: static constexpr struct OpenColorIO_v2_4::GpuShaderCreator::Impl* (OpenColorIO_v2_4::GpuShaderCreator::*_0)() = &_0GpuShaderCreator::getImpl; };
auto _0Protected = _0GpuShaderCreator::_0;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat_VectorFloat___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat::*_1)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat__VectorFloat(OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat*__instance) { __instance->~VectorFloat(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorFloat_VectorFloat(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorFloat(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt_VectorInt___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt::*_2)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt__VectorInt(OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt*__instance) { __instance->~VectorInt(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_S_VectorInt_VectorInt(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData::VectorInt(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_UniformData___1__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData(void* __instance, const OpenColorIO_v2_4::GpuShaderDesc::UniformData& _0) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData(_0); }
struct OpenColorIO_v2_4::GpuShaderDesc::UniformData& (OpenColorIO_v2_4::GpuShaderDesc::UniformData::*_3)(struct OpenColorIO_v2_4::GpuShaderDesc::UniformData&&) = &OpenColorIO_v2_4::GpuShaderDesc::UniformData::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData_UniformData(void* __instance) { ::new (__instance) OpenColorIO_v2_4::GpuShaderDesc::UniformData(); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GpuShaderDesc_S_UniformData__UniformData(OpenColorIO_v2_4::GpuShaderDesc::UniformData*__instance) { __instance->~UniformData(); }
class OpenColorIO_v2_4::ConfigIOProxy& (OpenColorIO_v2_4::ConfigIOProxy::*_4)(const class OpenColorIO_v2_4::ConfigIOProxy&) = &OpenColorIO_v2_4::ConfigIOProxy::operator=;
class c__N_OpenColorIO_v2_4_S_ConfigIOProxy_ConfigIOProxy___1__N_OpenColorIO_v2_4_S_ConfigIOProxyConfigIOProxy : public OpenColorIO_v2_4::ConfigIOProxy { public: c__N_OpenColorIO_v2_4_S_ConfigIOProxy_ConfigIOProxy___1__N_OpenColorIO_v2_4_S_ConfigIOProxyConfigIOProxy(const OpenColorIO_v2_4::ConfigIOProxy& _0): OpenColorIO_v2_4::ConfigIOProxy(_0) {}; std::vector<unsigned char, std::allocator<unsigned char>> getLutData(const char*) const { return {}; } std::basic_string<char, std::char_traits<char>, std::allocator<char>> getConfigData() const { return {}; } std::basic_string<char, std::char_traits<char>, std::allocator<char>> getFastLutFileHash(const char*) const { return {}; }  };
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_ConfigIOProxy_ConfigIOProxy___1__N_OpenColorIO_v2_4_S_ConfigIOProxy(void* __instance, const OpenColorIO_v2_4::ConfigIOProxy& _0) { ::new (__instance) c__N_OpenColorIO_v2_4_S_ConfigIOProxy_ConfigIOProxy___1__N_OpenColorIO_v2_4_S_ConfigIOProxyConfigIOProxy(_0); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBM_GradingRGBM_d_d_d_d(void* __instance, double red, double green, double blue, double master) { ::new (__instance) OpenColorIO_v2_4::GradingRGBM(red, green, blue, master); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBM_GradingRGBM___1_n4d(void* __instance, const double(& rgbm)[4]) { ::new (__instance) OpenColorIO_v2_4::GradingRGBM(rgbm); }
struct OpenColorIO_v2_4::GradingRGBM& (OpenColorIO_v2_4::GradingRGBM::*_5)(struct OpenColorIO_v2_4::GradingRGBM&&) = &OpenColorIO_v2_4::GradingRGBM::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingPrimary_GradingPrimary___N_OpenColorIO_v2_4_E_GradingStyle(void* __instance, OpenColorIO_v2_4::GradingStyle style) { ::new (__instance) OpenColorIO_v2_4::GradingPrimary(style); }
struct OpenColorIO_v2_4::GradingPrimary& (OpenColorIO_v2_4::GradingPrimary::*_6)(struct OpenColorIO_v2_4::GradingPrimary&&) = &OpenColorIO_v2_4::GradingPrimary::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingControlPoint_GradingControlPoint_f_f(void* __instance, float x, float y) { ::new (__instance) OpenColorIO_v2_4::GradingControlPoint(x, y); }
struct OpenColorIO_v2_4::GradingControlPoint& (OpenColorIO_v2_4::GradingControlPoint::*_7)(struct OpenColorIO_v2_4::GradingControlPoint&&) = &OpenColorIO_v2_4::GradingControlPoint::operator=;
class OpenColorIO_v2_4::GradingRGBCurve& (OpenColorIO_v2_4::GradingRGBCurve::*_8)(const class OpenColorIO_v2_4::GradingRGBCurve&) = &OpenColorIO_v2_4::GradingRGBCurve::operator=;
class c__N_OpenColorIO_v2_4_S_GradingRGBCurve_GradingRGBCurve___1__N_OpenColorIO_v2_4_S_GradingRGBCurveGradingRGBCurve : public OpenColorIO_v2_4::GradingRGBCurve { public: c__N_OpenColorIO_v2_4_S_GradingRGBCurve_GradingRGBCurve___1__N_OpenColorIO_v2_4_S_GradingRGBCurveGradingRGBCurve(const OpenColorIO_v2_4::GradingRGBCurve& _0): OpenColorIO_v2_4::GradingRGBCurve(_0) {}; std::shared_ptr<OpenColorIO_v2_4::GradingRGBCurve> createEditableCopy() const { return {}; } void validate() const {} bool isIdentity() const { return {}; } std::shared_ptr<const OpenColorIO_v2_4::GradingBSplineCurve> getCurve(OpenColorIO_v2_4::RGBCurveType) const { return {}; } std::shared_ptr<OpenColorIO_v2_4::GradingBSplineCurve> getCurve(OpenColorIO_v2_4::RGBCurveType) { return {}; }  };
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBCurve_GradingRGBCurve___1__N_OpenColorIO_v2_4_S_GradingRGBCurve(void* __instance, const OpenColorIO_v2_4::GradingRGBCurve& _0) { ::new (__instance) c__N_OpenColorIO_v2_4_S_GradingRGBCurve_GradingRGBCurve___1__N_OpenColorIO_v2_4_S_GradingRGBCurveGradingRGBCurve(_0); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBMSW_GradingRGBMSW_d_d_d_d_d_d(void* __instance, double red, double green, double blue, double master, double start, double width) { ::new (__instance) OpenColorIO_v2_4::GradingRGBMSW(red, green, blue, master, start, width); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBMSW_GradingRGBMSW___1_n6d(void* __instance, const double(& rgbmsw)[6]) { ::new (__instance) OpenColorIO_v2_4::GradingRGBMSW(rgbmsw); }
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingRGBMSW_GradingRGBMSW_d_d(void* __instance, double start, double width) { ::new (__instance) OpenColorIO_v2_4::GradingRGBMSW(start, width); }
struct OpenColorIO_v2_4::GradingRGBMSW& (OpenColorIO_v2_4::GradingRGBMSW::*_9)(struct OpenColorIO_v2_4::GradingRGBMSW&&) = &OpenColorIO_v2_4::GradingRGBMSW::operator=;
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_GradingTone_GradingTone___N_OpenColorIO_v2_4_E_GradingStyle(void* __instance, OpenColorIO_v2_4::GradingStyle style) { ::new (__instance) OpenColorIO_v2_4::GradingTone(style); }
struct OpenColorIO_v2_4::GradingTone& (OpenColorIO_v2_4::GradingTone::*_10)(struct OpenColorIO_v2_4::GradingTone&&) = &OpenColorIO_v2_4::GradingTone::operator=;
class OpenColorIO_v2_4::ColorSpaceMenuParameters& (OpenColorIO_v2_4::ColorSpaceMenuParameters::*_11)(const class OpenColorIO_v2_4::ColorSpaceMenuParameters&) = &OpenColorIO_v2_4::ColorSpaceMenuParameters::operator=;
class c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParametersColorSpaceMenuParameters : public OpenColorIO_v2_4::ColorSpaceMenuParameters { public: c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParametersColorSpaceMenuParameters(): OpenColorIO_v2_4::ColorSpaceMenuParameters() {}; void setConfig(std::shared_ptr<const OpenColorIO_v2_4::Config>) noexcept {} std::shared_ptr<const OpenColorIO_v2_4::Config> getConfig() const noexcept { return {}; } void setRole(const char*) noexcept {} const char* getRole() const noexcept { return {}; } void setIncludeColorSpaces(bool) noexcept {} bool getIncludeColorSpaces() const noexcept { return {}; } OpenColorIO_v2_4::SearchReferenceSpaceType getSearchReferenceSpaceType() const noexcept { return {}; } void setSearchReferenceSpaceType(OpenColorIO_v2_4::SearchReferenceSpaceType) noexcept {} void setIncludeNamedTransforms(bool) noexcept {} bool getIncludeNamedTransforms() const noexcept { return {}; } void setAppCategories(const char*) noexcept {} const char* getAppCategories() const noexcept { return {}; } void setEncodings(const char*) noexcept {} const char* getEncodings() const noexcept { return {}; } void setUserCategories(const char*) noexcept {} const char* getUserCategories() const noexcept { return {}; } void setIncludeRoles(bool) noexcept {} bool getIncludeRoles() const noexcept { return {}; } void addColorSpace(const char*) noexcept {} unsigned long long getNumAddedColorSpaces() const noexcept { return {}; } const char* getAddedColorSpace(unsigned long long) const noexcept { return {}; } void clearAddedColorSpaces() noexcept {}  };
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParameters(void* __instance) { ::new (__instance) c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParametersColorSpaceMenuParameters(); }
class c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParameters___1__N_OpenColorIO_v2_4_S_ColorSpaceMenuParametersColorSpaceMenuParameters : public OpenColorIO_v2_4::ColorSpaceMenuParameters { public: c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParameters___1__N_OpenColorIO_v2_4_S_ColorSpaceMenuParametersColorSpaceMenuParameters(const OpenColorIO_v2_4::ColorSpaceMenuParameters& _0): OpenColorIO_v2_4::ColorSpaceMenuParameters(_0) {}; void setConfig(std::shared_ptr<const OpenColorIO_v2_4::Config>) noexcept {} std::shared_ptr<const OpenColorIO_v2_4::Config> getConfig() const noexcept { return {}; } void setRole(const char*) noexcept {} const char* getRole() const noexcept { return {}; } void setIncludeColorSpaces(bool) noexcept {} bool getIncludeColorSpaces() const noexcept { return {}; } OpenColorIO_v2_4::SearchReferenceSpaceType getSearchReferenceSpaceType() const noexcept { return {}; } void setSearchReferenceSpaceType(OpenColorIO_v2_4::SearchReferenceSpaceType) noexcept {} void setIncludeNamedTransforms(bool) noexcept {} bool getIncludeNamedTransforms() const noexcept { return {}; } void setAppCategories(const char*) noexcept {} const char* getAppCategories() const noexcept { return {}; } void setEncodings(const char*) noexcept {} const char* getEncodings() const noexcept { return {}; } void setUserCategories(const char*) noexcept {} const char* getUserCategories() const noexcept { return {}; } void setIncludeRoles(bool) noexcept {} bool getIncludeRoles() const noexcept { return {}; } void addColorSpace(const char*) noexcept {} unsigned long long getNumAddedColorSpaces() const noexcept { return {}; } const char* getAddedColorSpace(unsigned long long) const noexcept { return {}; } void clearAddedColorSpaces() noexcept {}  };
extern "C" __declspec(dllexport) void c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParameters___1__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters(void* __instance, const OpenColorIO_v2_4::ColorSpaceMenuParameters& _0) { ::new (__instance) c__N_OpenColorIO_v2_4_S_ColorSpaceMenuParameters_ColorSpaceMenuParameters___1__N_OpenColorIO_v2_4_S_ColorSpaceMenuParametersColorSpaceMenuParameters(_0); }
