// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "OpenColorAppHelpers.h"
#include "OpenColorTypes.h"

using namespace System;
using namespace System::Runtime::InteropServices;

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::ColorSpaceMenuParameters(class ::OpenColorIO_v2_4::ColorSpaceMenuParameters* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*) native.ToPointer());
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::ColorSpaceMenuParameters(class ::OpenColorIO_v2_4::ColorSpaceMenuParameters* native, bool ownNativeInstance)
    : __ownsNativeInstance(ownNativeInstance)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::__CreateInstance(::System::IntPtr native, bool __ownsNativeInstance)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*) native.ToPointer(), __ownsNativeInstance);
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::~ColorSpaceMenuParameters()
{
    delete NativePtr;
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::AddColorSpace(::System::String^ name)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(name);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->addColorSpace(__arg0);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::GetAddedColorSpace(unsigned long long index)
{
    auto __arg0 = index;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getAddedColorSpace(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::ClearAddedColorSpaces()
{
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->clearAddedColorSpaces();
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::ColorSpaceMenuParameters()
{
    __ownsNativeInstance = true;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::ColorSpaceMenuParameters(OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters^ _0)
{
    __ownsNativeInstance = true;
}

::System::IntPtr OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::__Instance::get()
{
    return ::System::IntPtr(NativePtr);
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::__Instance::set(::System::IntPtr object)
{
    NativePtr = (class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)object.ToPointer();
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::Role::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getRole();
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::Role::set(::System::String^ role)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(role);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setRole(__arg0);
}

bool OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeColorSpaces::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getIncludeColorSpaces();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeColorSpaces::set(bool include)
{
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setIncludeColorSpaces(include);
}

OpenColorIO::OpenColorIO_v2_4::SearchReferenceSpaceType OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::SearchReferenceSpaceType::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getSearchReferenceSpaceType();
    return (OpenColorIO::OpenColorIO_v2_4::SearchReferenceSpaceType)___ret;
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::SearchReferenceSpaceType::set(OpenColorIO::OpenColorIO_v2_4::SearchReferenceSpaceType colorSpaceType)
{
    auto __arg0 = (enum ::OpenColorIO_v2_4::SearchReferenceSpaceType)colorSpaceType;
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setSearchReferenceSpaceType(__arg0);
}

bool OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeNamedTransforms::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getIncludeNamedTransforms();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeNamedTransforms::set(bool include)
{
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setIncludeNamedTransforms(include);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::AppCategories::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getAppCategories();
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::AppCategories::set(::System::String^ appCategories)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(appCategories);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setAppCategories(__arg0);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::Encodings::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getEncodings();
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::Encodings::set(::System::String^ encodings)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(encodings);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setEncodings(__arg0);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::UserCategories::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getUserCategories();
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::UserCategories::set(::System::String^ userCategories)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(userCategories);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setUserCategories(__arg0);
}

bool OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeRoles::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getIncludeRoles();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::IncludeRoles::set(bool include)
{
    ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->setIncludeRoles(include);
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuParameters::NumAddedColorSpaces::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuParameters*)NativePtr)->getNumAddedColorSpaces();
    return ___ret;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::ColorSpaceMenuHelper(class ::OpenColorIO_v2_4::ColorSpaceMenuHelper* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*) native.ToPointer());
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::ColorSpaceMenuHelper(class ::OpenColorIO_v2_4::ColorSpaceMenuHelper* native, bool ownNativeInstance)
    : __ownsNativeInstance(ownNativeInstance)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::__CreateInstance(::System::IntPtr native, bool __ownsNativeInstance)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*) native.ToPointer(), __ownsNativeInstance);
}

OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::~ColorSpaceMenuHelper()
{
    delete NativePtr;
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetName(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetUIName(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getUIName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetIndexFromName(::System::String^ name)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(name);
    auto __arg0 = ___arg0.c_str();
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getIndexFromName(__arg0);
    return ___ret;
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetIndexFromUIName(::System::String^ name)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(name);
    auto __arg0 = ___arg0.c_str();
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getIndexFromUIName(__arg0);
    return ___ret;
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetDescription(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getDescription(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetFamily(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getFamily(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetNumHierarchyLevels(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getNumHierarchyLevels(__arg0);
    return ___ret;
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetHierarchyLevel(unsigned long long idx, unsigned long long i)
{
    auto __arg0 = idx;
    auto __arg1 = i;
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getHierarchyLevel(__arg0, __arg1);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetNameFromUIName(::System::String^ uiName)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(uiName);
    auto __arg0 = ___arg0.c_str();
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getNameFromUIName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::GetUINameFromName(::System::String^ name)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(name);
    auto __arg0 = ___arg0.c_str();
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getUINameFromName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

::System::IntPtr OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::__Instance::get()
{
    return ::System::IntPtr(NativePtr);
}

void OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::__Instance::set(::System::IntPtr object)
{
    NativePtr = (class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)object.ToPointer();
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::ColorSpaceMenuHelper::NumColorSpaces::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::ColorSpaceMenuHelper*)NativePtr)->getNumColorSpaces();
    return ___ret;
}

OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LegacyViewingPipeline(class ::OpenColorIO_v2_4::LegacyViewingPipeline* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline^ OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline((class ::OpenColorIO_v2_4::LegacyViewingPipeline*) native.ToPointer());
}

OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LegacyViewingPipeline(class ::OpenColorIO_v2_4::LegacyViewingPipeline* native, bool ownNativeInstance)
    : __ownsNativeInstance(ownNativeInstance)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline^ OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::__CreateInstance(::System::IntPtr native, bool __ownsNativeInstance)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline((class ::OpenColorIO_v2_4::LegacyViewingPipeline*) native.ToPointer(), __ownsNativeInstance);
}

OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::~LegacyViewingPipeline()
{
    delete NativePtr;
}

::System::IntPtr OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::__Instance::get()
{
    return ::System::IntPtr(NativePtr);
}

void OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::__Instance::set(::System::IntPtr object)
{
    NativePtr = (class ::OpenColorIO_v2_4::LegacyViewingPipeline*)object.ToPointer();
}

bool OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LooksOverrideEnabled::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::LegacyViewingPipeline*)NativePtr)->getLooksOverrideEnabled();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LooksOverrideEnabled::set(bool enable)
{
    ((class ::OpenColorIO_v2_4::LegacyViewingPipeline*)NativePtr)->setLooksOverrideEnabled(enable);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LooksOverride::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::LegacyViewingPipeline*)NativePtr)->getLooksOverride();
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::LegacyViewingPipeline::LooksOverride::set(::System::String^ looks)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(looks);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::LegacyViewingPipeline*)NativePtr)->setLooksOverride(__arg0);
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider::MixingSlider(class ::OpenColorIO_v2_4::MixingSlider* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider^ OpenColorIO::OpenColorIO_v2_4::MixingSlider::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingSlider((class ::OpenColorIO_v2_4::MixingSlider*) native.ToPointer());
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider::MixingSlider(class ::OpenColorIO_v2_4::MixingSlider* native, bool ownNativeInstance)
    : __ownsNativeInstance(ownNativeInstance)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider^ OpenColorIO::OpenColorIO_v2_4::MixingSlider::__CreateInstance(::System::IntPtr native, bool __ownsNativeInstance)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingSlider((class ::OpenColorIO_v2_4::MixingSlider*) native.ToPointer(), __ownsNativeInstance);
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider::~MixingSlider()
{
    delete NativePtr;
}

float OpenColorIO::OpenColorIO_v2_4::MixingSlider::SliderToMixing(float sliderUnits)
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->sliderToMixing(sliderUnits);
    return ___ret;
}

float OpenColorIO::OpenColorIO_v2_4::MixingSlider::MixingToSlider(float mixingUnits)
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->mixingToSlider(mixingUnits);
    return ___ret;
}

::System::IntPtr OpenColorIO::OpenColorIO_v2_4::MixingSlider::__Instance::get()
{
    return ::System::IntPtr(NativePtr);
}

void OpenColorIO::OpenColorIO_v2_4::MixingSlider::__Instance::set(::System::IntPtr object)
{
    NativePtr = (class ::OpenColorIO_v2_4::MixingSlider*)object.ToPointer();
}

float OpenColorIO::OpenColorIO_v2_4::MixingSlider::SliderMinEdge::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->getSliderMinEdge();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::MixingSlider::SliderMinEdge::set(float sliderMixingMinEdge)
{
    ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->setSliderMinEdge(sliderMixingMinEdge);
}

float OpenColorIO::OpenColorIO_v2_4::MixingSlider::SliderMaxEdge::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->getSliderMaxEdge();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::MixingSlider::SliderMaxEdge::set(float sliderMixingMaxEdge)
{
    ((class ::OpenColorIO_v2_4::MixingSlider*)NativePtr)->setSliderMaxEdge(sliderMixingMaxEdge);
}

OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::MixingColorSpaceManager(class ::OpenColorIO_v2_4::MixingColorSpaceManager* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager((class ::OpenColorIO_v2_4::MixingColorSpaceManager*) native.ToPointer());
}

OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::MixingColorSpaceManager(class ::OpenColorIO_v2_4::MixingColorSpaceManager* native, bool ownNativeInstance)
    : __ownsNativeInstance(ownNativeInstance)
{
    NativePtr = native;
}

OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::__CreateInstance(::System::IntPtr native, bool __ownsNativeInstance)
{
    return gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager((class ::OpenColorIO_v2_4::MixingColorSpaceManager*) native.ToPointer(), __ownsNativeInstance);
}

OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::~MixingColorSpaceManager()
{
    delete NativePtr;
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::GetMixingSpaceUIName(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getMixingSpaceUIName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SetSelectedMixingSpace(::System::String^ mixingSpace)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(mixingSpace);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->setSelectedMixingSpace(__arg0);
}

::System::String^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::GetMixingEncodingName(unsigned long long idx)
{
    auto __arg0 = idx;
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getMixingEncodingName(__arg0);
    if (___ret == nullptr) return nullptr;
    return (___ret == 0 ? nullptr : clix::marshalString<clix::E_UTF8>(___ret));
}

void OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SetSelectedMixingEncoding(::System::String^ mixingEncoding)
{
    auto ___arg0 = clix::marshalString<clix::E_UTF8>(mixingEncoding);
    auto __arg0 = ___arg0.c_str();
    ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->setSelectedMixingEncoding(__arg0);
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::GetSlider()
{
    auto &___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getSlider();
    return (OpenColorIO::OpenColorIO_v2_4::MixingSlider^)((&___ret == nullptr) ? nullptr : gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingSlider((class ::OpenColorIO_v2_4::MixingSlider*)&___ret));
}

OpenColorIO::OpenColorIO_v2_4::MixingSlider^ OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::GetSlider(float sliderMixingMinEdge, float sliderMixingMaxEdge)
{
    auto &___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getSlider(sliderMixingMinEdge, sliderMixingMaxEdge);
    return (OpenColorIO::OpenColorIO_v2_4::MixingSlider^)((&___ret == nullptr) ? nullptr : gcnew ::OpenColorIO::OpenColorIO_v2_4::MixingSlider((class ::OpenColorIO_v2_4::MixingSlider*)&___ret));
}

::System::IntPtr OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::__Instance::get()
{
    return ::System::IntPtr(NativePtr);
}

void OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::__Instance::set(::System::IntPtr object)
{
    NativePtr = (class ::OpenColorIO_v2_4::MixingColorSpaceManager*)object.ToPointer();
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::NumMixingSpaces::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getNumMixingSpaces();
    return ___ret;
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SelectedMixingSpaceIdx::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getSelectedMixingSpaceIdx();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SelectedMixingSpaceIdx::set(unsigned long long idx)
{
    auto __arg0 = idx;
    ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->setSelectedMixingSpaceIdx(__arg0);
}

bool OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::IsPerceptuallyUniform::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->isPerceptuallyUniform();
    return ___ret;
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::NumMixingEncodings::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getNumMixingEncodings();
    return ___ret;
}

unsigned long long OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SelectedMixingEncodingIdx::get()
{
    auto ___ret = ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->getSelectedMixingEncodingIdx();
    return ___ret;
}

void OpenColorIO::OpenColorIO_v2_4::MixingColorSpaceManager::SelectedMixingEncodingIdx::set(unsigned long long idx)
{
    auto __arg0 = idx;
    ((class ::OpenColorIO_v2_4::MixingColorSpaceManager*)NativePtr)->setSelectedMixingEncodingIdx(__arg0);
}

